name: hello-world
on: 
  push:  
    branches: [development,staging,main]
    
  workflow_dispatch:
  
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      
    steps:
      - name: Print Payload Values
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.foo }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
          
      - name: my-step
        run: echo "Hello World!${{github.ref}}"
