name: hello-world
on: 
  push:  
    branches: [development,staging,main]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      
    steps:
      - name: my-step
        run: echo "Hello World!${{github.ref}}"
