name: hello-world
on: 
  push:  
    branches: [development,staging,main]
    
  workflow_dispatch:
  
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      
    steps:
      - name: Print Payload Values
        run: |
          echo "Key: ${{ github.event.client_payload.key }}"
          echo "Value: ${{ github.event.client_payload.value }}"
          
      - name: my-step
        run: echo "Hello World!${{github.ref}}"
