on:
  repository_dispatch:

env:
  webflow_env: ${{ github.event.client_payload.webflow_env }}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name : print-webflowQuery
      run: echo "print webflowQuery ${{env.webflow_query}}"

    - name: Configuration For Development Branch
      if: ${{ webflow_env == 'development' }}
      run: |
            echo "SLACK_CHANNEL=" >> $GITHUB_ENV 

      
      
         
  
